spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mapstruct
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate: org.hibernate.dialect.PostgresSQLDialect


server:
  port: 8090





